from copy import deepcopy
from dataclasses import dataclass, field
from types import MappingProxyType
from typing import Any, AsyncIterator, Dict, Iterator, List, Literal, Mapping, Optional, Protocol, runtime_checkable

EVENT_SCHEMA_VERSION = "1.0"
RESERVED_EVENT_TYPES = {
    "text_delta",
    "tool_call_delta",
    "tool_result",
    "phase",
    "usage",
    "completed",
    "error",
}


@dataclass
class NormalizedToolFunction:
    name: str
    arguments: str = ""


@dataclass
class NormalizedToolCall:
    id: str
    type: str = "function"
    function: Optional[NormalizedToolFunction] = None
    payload: Optional[Dict[str, Any]] = None
    item_id: Optional[str] = None
    status: Optional[str] = None
    provider_extras: Optional[Dict[str, Any]] = None


@dataclass(frozen=True)
class ApplyPatchCall:
    """Isolated Apply Patch request passed to the caller's executor.

    ``call_id`` correlates the required provider output. ``item_id`` identifies
    the response item itself. The operation and provider extras are copied
    before execution so application code cannot mutate Chat history by accident.
    """

    item_id: Optional[str]
    call_id: str
    status: str
    operation: Mapping[str, Any]
    caller: Optional[Mapping[str, Any]] = None
    agent: Optional[Mapping[str, Any]] = None
    created_by: Optional[str] = None
    provider_extras: Mapping[str, Any] = field(
        default_factory=lambda: MappingProxyType({})
    )

    @classmethod
    def from_normalized(cls, tool_call: NormalizedToolCall) -> "ApplyPatchCall":
        """Build an isolated executor value from one normalized provider call."""
        payload = deepcopy(tool_call.payload or {})
        operation = payload.pop("operation", {})
        caller = payload.pop("caller", None)
        agent = payload.pop("agent", None)
        created_by = payload.pop("created_by", None)
        extras = deepcopy(tool_call.provider_extras or {})
        if caller is not None and not isinstance(caller, Mapping):
            extras.setdefault("caller", caller)
            caller = None
        if agent is not None and not isinstance(agent, Mapping):
            extras.setdefault("agent", agent)
            agent = None
        for key, value in payload.items():
            extras.setdefault(key, value)
        return cls(
            item_id=tool_call.item_id,
            call_id=tool_call.id,
            status=tool_call.status or "",
            operation=MappingProxyType(dict(operation)),
            caller=MappingProxyType(dict(caller)) if caller is not None else None,
            agent=MappingProxyType(dict(agent)) if agent is not None else None,
            created_by=created_by,
            provider_extras=MappingProxyType(extras),
        )


@dataclass
class PendingOutput:
    """Generated bytes or a provider file awaiting local chat capture."""

    kind: Literal["image", "file"]
    filename: Optional[str] = None
    data: Optional[bytes] = field(default=None, repr=False)
    file_id: Optional[str] = None
    container_id: Optional[str] = None


@dataclass
class NormalizedAssistantMessage:
    role: str = "assistant"
    content: Optional[str] = None
    reasoning: Optional[str] = None
    encrypted_content: Optional[str] = None
    sources: List[Dict[str, Any]] = field(default_factory=list)
    images: List[Dict[str, Any]] = field(default_factory=list)
    files: List[Dict[str, Any]] = field(default_factory=list)
    tool_calls: List[NormalizedToolCall] = field(default_factory=list)
    provider_extras: Optional[Dict[str, Any]] = None
    pending_outputs: List[PendingOutput] = field(default_factory=list, repr=False)


@dataclass
class NormalizedCompletionResult:
    message: NormalizedAssistantMessage
    finish_reason: Optional[str] = None
    model: Optional[str] = None
    usage: Optional[Dict[str, Any]] = None
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class RuntimeTerminalMetadata:
    finish_reason: Optional[str] = None
    model: Optional[str] = None
    usage: Optional[Dict[str, Any]] = None
    response_text: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class RuntimeErrorPayload:
    message: str
    code: Optional[str] = None
    retriable: bool = False
    details: Optional[Dict[str, Any]] = None


@dataclass
class RuntimeStreamEvent:
    type: Literal[
        "text_delta",
        "tool_call_delta",
        "tool_result",
        "phase",
        "usage",
        "completed",
        "error",
    ]
    index: int
    data: Dict[str, Any]
    schema_version: str = EVENT_SCHEMA_VERSION


@runtime_checkable
class RuntimeAdapter(Protocol):
    """
    RuntimeAdapter owns only provider I/O and normalization.
    Prompt compilation and template expansion remain Chat-layer responsibilities.

    ``runtime_family`` tells Chat which provider-native input and output shapes
    the adapter can carry. Custom Responses adapters should use ``"responses"``.
    """

    runtime_family: Literal["chat_completions", "responses"]

    def create_completion(self, messages: List[Dict[str, Any]], **kwargs: Any) -> NormalizedCompletionResult:
        ...

    async def create_completion_a(self, messages: List[Dict[str, Any]], **kwargs: Any) -> NormalizedCompletionResult:
        ...

    def stream_completion(self, messages: List[Dict[str, Any]], **kwargs: Any) -> Iterator[RuntimeStreamEvent]:
        ...

    async def stream_completion_a(self, messages: List[Dict[str, Any]], **kwargs: Any) -> AsyncIterator[RuntimeStreamEvent]:
        ...
