"""Local values and storage for files generated during a chat."""

from __future__ import annotations

import hashlib
import os
import re
import shutil
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Mapping, Optional
from urllib.parse import urlparse

from .defaults import CHATSNACK_ASSETS


_ASSET_ID = re.compile(r"^sha256:([0-9a-f]{64})$")
_UNSAFE_FILENAME = re.compile(r"[^A-Za-z0-9._ ()-]+")
_WINDOWS_RESERVED = {
    "CON",
    "PRN",
    "AUX",
    "NUL",
    *(f"COM{number}" for number in range(1, 10)),
    *(f"LPT{number}" for number in range(1, 10)),
}


class GeneratedAssetError(RuntimeError):
    """Base error for generated assets that cannot be stored or read."""


class AssetReferenceError(ValueError, GeneratedAssetError):
    """Raised when an asset digest or filename is unsafe or malformed."""


class AssetMissingError(FileNotFoundError, GeneratedAssetError):
    """Raised when a saved chat points to an asset that is no longer present."""


class AssetCorruptError(GeneratedAssetError):
    """Raised when local asset bytes no longer match the digest in the chat."""


class AssetUnavailableError(GeneratedAssetError):
    """Raised when a file has only a remote reference and no local bytes."""


def _asset_root() -> Path:
    """Resolve the current environment-aware assets stash."""
    return Path(CHATSNACK_ASSETS.refresh().path)


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _image_extension(data: bytes) -> Optional[str]:
    if data.startswith(b"\x89PNG\r\n\x1a\n"):
        return "png"
    if data.startswith(b"\xff\xd8\xff"):
        return "jpg"
    if len(data) >= 12 and data.startswith(b"RIFF") and data[8:12] == b"WEBP":
        return "webp"
    return None


def _safe_filename(filename: Optional[str], *, fallback: str) -> str:
    """Turn a provider filename into one readable basename."""
    raw = str(filename or "").replace("\\", "/").rsplit("/", 1)[-1]
    safe = _UNSAFE_FILENAME.sub("_", raw).strip(" .")
    if not safe or safe in {".", ".."}:
        safe = fallback
    if Path(safe).stem.upper() in _WINDOWS_RESERVED:
        safe = f"_{safe}"
    if len(safe) > 180:
        suffix = Path(safe).suffix[:20]
        safe = f"{Path(safe).stem[: 180 - len(suffix)]}{suffix}"
    return safe


def capture_asset(data: bytes, *, filename: Optional[str] = None, kind: str = "file") -> dict[str, str]:
    """Store generated bytes atomically and return their YAML reference."""
    if not isinstance(data, (bytes, bytearray)):
        raise TypeError("Generated asset data must be bytes.")
    payload = bytes(data)
    digest = hashlib.sha256(payload).hexdigest()
    if kind == "image":
        extension = _image_extension(payload)
        if extension is None:
            raise GeneratedAssetError("Generated image has an unsupported file signature.")
        fallback = f"gpt-image-{digest[:16]}.{extension}"
    else:
        fallback = f"generated-file-{digest[:16]}.bin"
    safe_name = _safe_filename(filename, fallback=fallback)
    destination_dir = _asset_root() / "sha256" / digest
    destination = destination_dir / safe_name
    destination_dir.mkdir(parents=True, exist_ok=True)

    if destination.exists() and _sha256(destination) == digest:
        return {"asset": f"sha256:{digest}", "filename": safe_name}

    temp_path = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="wb",
            dir=destination_dir,
            prefix=f".{safe_name}.",
            suffix=".tmp",
            delete=False,
        ) as temp_file:
            temp_file.write(payload)
            temp_file.flush()
            os.fsync(temp_file.fileno())
            temp_path = Path(temp_file.name)
        os.replace(temp_path, destination)
    finally:
        if temp_path is not None:
            temp_path.unlink(missing_ok=True)

    if _sha256(destination) != digest:
        raise AssetCorruptError(f"Generated asset failed its digest check after capture: {safe_name}")

    return {"asset": f"sha256:{digest}", "filename": safe_name}


def resolve_asset_path(asset: str, filename: str, *, verify: bool = True) -> Path:
    """Resolve a YAML asset reference, with strict digest checks by default."""
    match = _ASSET_ID.fullmatch(str(asset or ""))
    if match is None:
        raise AssetReferenceError(f"Invalid generated asset reference: {asset!r}")
    digest = match.group(1)
    safe_name = _safe_filename(filename, fallback="")
    if not filename or safe_name != filename:
        raise AssetReferenceError(f"Unsafe generated asset filename: {filename!r}")
    path = _asset_root() / "sha256" / digest / safe_name
    if not path.is_file():
        raise AssetMissingError(f"Generated asset is missing: {asset} ({safe_name})")
    if verify and _sha256(path) != digest:
        raise AssetCorruptError(f"Generated asset failed its digest check: {asset} ({safe_name})")
    return path


@dataclass(frozen=True)
class ChatFile(os.PathLike[str]):
    """One image or file returned by an assistant turn.

    Captured assets and ordinary local paths can be read or passed into a later
    chat. Remote-only references keep their provider metadata for inspection.
    """

    filename: Optional[str] = None
    asset: Optional[str] = None
    file_id: Optional[str] = None
    container_id: Optional[str] = None
    url: Optional[str] = None
    kind: str = "file"
    _path: Optional[str] = field(default=None, repr=False)

    @classmethod
    def from_reference(cls, reference: Mapping[str, Any], *, kind: str = "file") -> "ChatFile":
        """Build a value from an authored or provider output reference."""
        path = reference.get("path")
        filename = reference.get("filename")
        if not filename and path:
            filename = Path(str(path)).name
        if not filename and reference.get("url"):
            filename = Path(urlparse(str(reference["url"])).path).name or None
        return cls(
            filename=str(filename) if filename else None,
            asset=str(reference["asset"]) if reference.get("asset") else None,
            file_id=str(reference["file_id"]) if reference.get("file_id") else None,
            container_id=(
                str(reference["container_id"]) if reference.get("container_id") else None
            ),
            url=str(reference["url"]) if reference.get("url") else None,
            kind=kind,
            _path=str(path) if path else None,
        )

    @property
    def path(self) -> Optional[Path]:
        """Return the local path, checking captured asset integrity first."""
        if self.asset:
            if not self.filename:
                raise AssetReferenceError(f"Generated asset {self.asset} has no filename.")
            return resolve_asset_path(self.asset, self.filename)
        if self._path:
            return Path(self._path)
        return None

    @property
    def captured(self) -> bool:
        """Return whether verified local bytes are available."""
        try:
            path = self.path
            return path is not None and path.is_file()
        except GeneratedAssetError:
            return False

    def read_bytes(self) -> bytes:
        """Read local bytes, raising clearly for remote, missing, or corrupt files."""
        path = self.path
        if path is None:
            raise AssetUnavailableError(
                f"{self.filename or self.file_id or self.url or 'This file'} has no local bytes."
            )
        if not path.is_file():
            raise AssetMissingError(f"Generated file is missing: {path}")
        return path.read_bytes()

    def save_as(self, destination: os.PathLike[str] | str) -> Path:
        """Copy the verified local file to a caller-selected path."""
        source = self.path
        if source is None:
            raise AssetUnavailableError(
                f"{self.filename or self.file_id or self.url or 'This file'} has no local bytes."
            )
        target = Path(destination)
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(source, target)
        return target

    def _attachment_reference(self) -> dict[str, str]:
        """Return the canonical reference used when this value enters a new chat."""
        if self.asset and self.filename:
            return {"asset": self.asset, "filename": self.filename}
        if self._path:
            reference = {"path": self._path}
        elif self.file_id:
            reference = {"file_id": self.file_id}
        elif self.url:
            reference = {"url": self.url}
        else:
            raise AssetUnavailableError("This ChatFile has no usable attachment source.")
        if self.filename:
            reference["filename"] = self.filename
        return reference

    def __fspath__(self) -> str:
        path = self.path
        if path is None:
            raise AssetUnavailableError("This ChatFile has no local path.")
        return os.fspath(path)
